'' This file is here to save the dev from having to paste this lengthy
'' uri in every puml file. It also allows easy switching of themes
'' if the need ever arises
@startuml
!theme utku from https://gist.githubusercontent.com/utkusarioglu/20ccbe51bfc362b9fe12e894237eccc3/raw/666b8bf2e8508b2139846a7b9e764c4389a60f41/
skinparam actor {
  FontColor $SECONDARY_TEXT
}
skinparam node {
  FontColor $SECONDARY_TEXT
  BackgroundColor $LIGHT
}

skinparam linetype ortho

skinparam boundary {
  FontColor $SECONDARY_TEXT
}
@enduml
